import { cn } from "@/shared/lib/utils";
import { Header } from "@/shared/widgets/header";
import { Metadata } from "next";
import { Overpass } from "next/font/google";
import "./globals.css";

const overpass = Overpass({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-zinc-950 antialiased text-neutral-50 container py-10 tracking-wide",
          overpass.className,
        )}
      >
        <Header />
        <main className="min-h-screen w-full pt-16">{children}</main>
      </body>
    </html>
  );
}
